apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secrets
type: Opaque
data:
  PG_USER_EMAIL: c3VwZXJtYW5AZ29vZ2xlLmNvbQ==  # "superman@google.com" en base64
  DB_PASSWORD: RXNVblBhYXN3b3JkU2VjcmV0b2Vu   # EsUnPaaswordSecretoen base64
