apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=  # "postgres" en base64
  DB_PASSWORD: RXNVblBhYXN3b3JkU2VjcmV0b2Vu   # EsUnPaaswordSecretoen base64
